name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: sunghwanlee/swpp202101-ci

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure.sh /llvmscript/llvm-12.0-releaseassert/bin
    - name: make
      run: make
    - name: make test
      run: make test
