name: Compute benchmark costs

on:
  push:
    branches: [ main ]

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/cookiehcl/swpp202101-team4/swpp202101-ci
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure Makefile
        run: ./configure.sh $LLVM_DIR
      - name: make
        run: make
      - name: wait for previous runs
        uses: ahmadnassri/action-workflow-queue@v1
        with:
          timeout: 3600000
          delay: 60000
      - name: initialize
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git checkout BENCHMARK_COSTS
          git pull
          git merge -X theirs main -m "${{ github.event.commits[0].message }}"
      - name: compute benchmarks
        run: python3 compute-benchmarks.py $INTERPRETER $BENCHMARK_DIR
      - name: commit
        run: |
          rm -rf .github/workflows/
          git add .
          git commit --amend -m "Update benchmarks costs" -m "${{ github.event.commits[0].message }}"
          git push
