name: Publish docker package

on:
  push:
    branches: [ DOCKER ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and publish
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/cookiehcl/swpp202101-team4/swpp202101-ci:latest
